import React, { useState } from 'react';
import { TaskAnalysis, WorkTask } from '../types';
import { Copy, Check, MessageSquare, Zap, Terminal, Sparkles } from 'lucide-react';
import { motion } from 'motion/react';
import { cn } from '../lib/utils';

interface AutomationPlanProps {
  tasks: WorkTask[];
  analyses: TaskAnalysis[];
}

export default function AutomationPlan({ tasks, analyses }: AutomationPlanProps) {
  const [copiedId, setCopiedId] = useState<string | null>(null);

  const copyPrompt = (id: string, text: string) => {
    navigator.clipboard.writeText(text);
    setCopiedId(id);
    setTimeout(() => setCopiedId(null), 2000);
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between border-b border-slate-200 pb-4">
        <div>
          <h2 className="text-lg font-semibold tracking-tight text-slate-800">Deployment Roadmap</h2>
          <p className="text-xs text-slate-500">Actionable implementation plans generated by AI</p>
        </div>
        <div className="flex gap-2">
           <span className="px-3 py-1 bg-slate-100 text-[10px] font-bold rounded-full text-slate-500">STATUS: READY</span>
        </div>
      </div>

      <div className="grid grid-cols-1 gap-6">
        {analyses.sort((a, b) => b.automationScore - a.automationScore).map((analysis, idx) => {
          const task = tasks.find(t => t.id === analysis.taskId);
          if (!task) return null;

          return (
            <motion.div
              key={analysis.taskId}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: idx * 0.1 }}
              className="bg-white rounded-3xl border border-slate-200 shadow-sm overflow-hidden"
            >
              <div className="p-6 flex flex-col md:flex-row gap-8">
                <div className="md:w-1/3 flex flex-col">
                  <div className="flex items-center gap-3 mb-4">
                    <div className="w-10 h-10 rounded-xl bg-blue-100 flex items-center justify-center shrink-0">
                      <Zap className="text-blue-600" size={20} fill="currentColor" />
                    </div>
                    <div>
                      <h3 className="text-sm font-bold text-slate-800 uppercase tracking-tight leading-tight">{task.title}</h3>
                      <p className="text-[10px] text-blue-600 font-bold uppercase tracking-widest mt-0.5">{analysis.automationTool}</p>
                    </div>
                  </div>
                  
                  <div className="space-y-4 flex-1">
                    <div className="bg-slate-50 rounded-2xl p-4 border border-slate-100">
                      <p className="text-[11px] text-slate-500 leading-relaxed font-medium italic">
                        "{analysis.reasoning}"
                      </p>
                    </div>

                    <div className="grid grid-cols-2 gap-4">
                       <div className="space-y-1">
                          <p className="label-caps !text-[9px]">Repetition</p>
                          <div className="flex items-center gap-2">
                            <div className="flex-1 h-1 bg-slate-100 rounded-full overflow-hidden">
                              <div className="h-full bg-blue-500" style={{ width: `${task.repetitiveness * 100}%` }} />
                            </div>
                            <span className="text-[10px] font-mono text-slate-600 font-bold">{Math.round(task.repetitiveness * 100)}%</span>
                          </div>
                       </div>
                       <div className="space-y-1">
                          <p className="label-caps !text-[9px]">Complexity</p>
                          <span className="text-[10px] font-mono text-slate-600 font-bold">LOW-MID</span>
                       </div>
                    </div>
                  </div>

                  <div className="mt-6 pt-4 border-t border-slate-50 flex items-center justify-between">
                     <div className="flex flex-col">
                        <span className="label-caps !text-[8px]">Savings Potential</span>
                        <span className="text-xs font-mono font-bold text-emerald-600">+{analysis.savingsEstimate}</span>
                     </div>
                     <div className="flex -space-x-1">
                        {[1,2,3].map(i => (
                           <div key={i} className={cn("w-4 h-4 rounded-full border-2 border-white bg-slate-200 flex items-center justify-center text-[6px] font-bold text-slate-400", i === 1 && "bg-blue-500 text-white border-blue-100")}>
                              {i}
                           </div>
                        ))}
                     </div>
                  </div>
                </div>

                <div className="md:w-2/3 flex flex-col">
                  <div className="flex items-center justify-between mb-3">
                    <p className="label-caps">AI Efficiency Prompt</p>
                    <button
                      onClick={() => copyPrompt(analysis.taskId, analysis.suggestedPrompt)}
                      className="flex items-center gap-1.5 text-[10px] font-bold uppercase text-slate-400 hover:text-blue-600 transition-colors"
                    >
                      {copiedId === analysis.taskId ? (
                        <>
                          <Check size={12} strokeWidth={3} className="text-emerald-500" /> Copied
                        </>
                      ) : (
                        <>
                          <Copy size={12} /> Copy
                        </>
                      )}
                    </button>
                  </div>

                  <div className="relative flex-1 group">
                    <div className="absolute inset-0 bg-slate-50 rounded-2xl border border-slate-100 font-mono text-[11px] leading-relaxed text-slate-600 p-5 group-hover:border-blue-200 transition-colors overflow-y-auto">
                      {analysis.suggestedPrompt}
                    </div>
                    <div className="absolute bottom-3 right-3 text-slate-200 pointer-events-none">
                       <Terminal size={14} />
                    </div>
                  </div>
                  
                  <button className="w-full mt-4 py-2.5 bg-slate-100 text-slate-600 text-[10px] font-bold rounded-xl hover:bg-blue-50 hover:text-blue-600 transition-all uppercase tracking-widest border border-slate-200 border-dashed">
                      Initialize Integration Flow
                  </button>
                </div>
              </div>
            </motion.div>
          );
        })}
      </div>
    </div>
  );
}
